#
# ------------------------------------------------------------------------------
# Visual Studio light theme for FlatLaf
# ------------------------------------------------------------------------------
# (c) 2026 CrayZor. All rights reserved
# ------------------------------------------------------------------------------
#
name = FlatLafVSLight
dark = false

# ---- Main colors ----
@background = #F3F3F3
@foreground = #1E1E1E
@accentColor = #007ACC
@accentLateColor = #005A9E

@selectionBackground = #CCE4FC
@selectionForeground = #1E1E1E
@focusedBorderColor = #007ACC
@borderColor = #D4D4D4
@disabledForeground = #A6A6A6

# ---- UI components ----

# Buttons
Button.background = #E1E1E1
Button.foreground = #1E1E1E
Button.hoverBackground = #EBF4FC
Button.hoverBorderColor = #007ACC
Button.focusedBorderColor = #007ACC
Button.borderColor = #CCCCCC
Button.arc = 0

# TextFields
TextComponent.arc = 0
TextField.background = #FFFFFF
TextField.foreground = #1E1E1E
TextField.selectedTextColor = #1E1E1E
TextField.selectionBackground = #ADD6FF

# Lists, Tables, Tree lists
List.background = #FFFFFF
List.foreground = #1E1E1E
List.selectionBackground = #CCE4FC
List.selectionForeground = #1E1E1E

Table.background = #FFFFFF
Table.gridColor = #D4D4D4
Table.selectionBackground = #CCE4FC
Table.selectionForeground = #1E1E1E
TableHeader.background = #EEEEEE
TableHeader.foreground = #1E1E1E

# Panels and scrollbars
Panel.background = #F3F3F3
ScrollPane.background = #FFFFFF

ScrollBar.track = #F3F3F3
ScrollBar.thumb = #C2C2C2
ScrollBar.thumbHover = #9E9E9E
ScrollBar.width = 10

# Tabs
TabbedPane.showTabSeparators = true
TabbedPane.tabSeparatorsColor = #D4D4D4
TabbedPane.selectedBackground = #FFFFFF
TabbedPane.background = #EEEEEE
TabbedPane.foreground = #555555
TabbedPane.selectedForeground = #007ACC
TabbedPane.underlineColor = #007ACC
TabbedPane.contentAreaColor = #D4D4D4

# Menu
MenuBar.background = #F3F3F3
MenuBar.foreground = #1E1E1E
MenuItem.background = #F3F3F3
MenuItem.foreground = #1E1E1E
MenuItem.selectionBackground = #CCE4FC
MenuItem.selectionForeground = #1E1E1E

# Panel title
TitlePane.background = #F3F3F3
TitlePane.foreground = #1E1E1E
TitlePane.inactiveBackground = #F3F3F3
TitlePane.inactiveForeground = #808080