#
# ------------------------------------------------------------------------------
# Visual Studio dark theme for FlatLaf
# ------------------------------------------------------------------------------
# (c) 2026 CrayZor. All rights reserved
# ------------------------------------------------------------------------------
#
name = FlatLafVSDark
dark = true

# ---- Main colors ----
@background = #1E1E1E
@foreground = #D4D4D4
@accentColor = #007ACC
@accentLateColor = #1C97EA

@selectionBackground = #264F78
@selectionForeground = #FFFFFF
@focusedBorderColor = #007ACC
@borderColor = #3F3F46
@disabledForeground = #656565

# ---- UI components ----

# Buttons
Button.background = #2D2D30
Button.foreground = #F1F1F1
Button.hoverBackground = #3E3E40
Button.hoverBorderColor = #007ACC
Button.focusedBorderColor = #007ACC
Button.borderColor = #3F3F46
Button.arc = 5

# TextFields
TextComponent.arc = 0
TextField.background = #252526
TextField.foreground = #FFF
TextField.selectedTextColor = #FFFFFF
TextField.selectionBackground = #264F78

# Lists, Tables, Tree lists
List.background = #252526
List.foreground = #D4D4D4
List.selectionBackground = #264F78
List.selectionForeground = #FFFFFF

Table.background = #252526
Table.gridColor = #2D2D32
Table.selectionBackground = #264F78
Table.selectionForeground = #FFFFFF
TableHeader.background = #2D2D30
TableHeader.foreground = #F1F1F1

# Panels and scrollbars
Panel.background = #1E1E1E
ScrollPane.background = #252526

ScrollBar.track = #1E1E1E
ScrollBar.thumb = #46464A
ScrollBar.thumbHover = #555559
ScrollBar.width = 10

# Tabs
TabbedPane.showTabSeparators = true
TabbedPane.tabSeparatorsColor = #2D2D30
TabbedPane.selectedBackground = #1E1E1E
TabbedPane.background = #2D2D30
TabbedPane.foreground = #969696
TabbedPane.selectedForeground = #007ACC
TabbedPane.underlineColor = #007ACC
TabbedPane.contentAreaColor = #2F2F32

# Menu
MenuBar.background = #2D2D30
MenuBar.foreground = #F1F1F1
MenuItem.background = #2D2D30
MenuItem.foreground = #F1F1F1
MenuItem.selectionBackground = #3E3E40
MenuItem.selectionForeground = #FFFFFF

# Panel title
TitlePane.background = #2D2D30
TitlePane.foreground = #969696
TitlePane.activeForeground = #F1F1F1
TitlePane.inactiveBackground = #2D2D30
TitlePane.inactiveForeground = #656565