/*
 * -----------------------------------------------------------------------------
 * Orion IDE Project
 * -----------------------------------------------------------------------------
 * (c) 2026 CrayZor. All rights reserved
 * -----------------------------------------------------------------------------
 */

/*
 *******************************************************************************
 * Code editor panel class
 *******************************************************************************
 * Editor UI control methods
 *******************************************************************************
 */
package orion.ide.ui;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import org.fife.ui.rsyntaxtextarea.*;
import org.fife.ui.rtextarea.*;

public class CodeEditorPanel extends javax.swing.JPanel {
    
    private final String iconsFolder = MainWindow.iconsFolder;
    private final String fileExtension = MainWindow.newFileExtension;

    // Set toolbar buttons icons
    public final FlatSVGIcon goToViewIcon = new FlatSVGIcon("resources/icons/" + iconsFolder + "/go_to_view.svg", 16, 16);
    public final FlatSVGIcon structureInsertIcon = new FlatSVGIcon("resources/icons/" + iconsFolder + "/ins_structure.svg", 16, 16);
    public final FlatSVGIcon enumerationInsertIcon = new FlatSVGIcon("resources/icons/" + iconsFolder + "/ins_enum.svg", 16, 16);
    public final FlatSVGIcon functionInsertIcon = new FlatSVGIcon("resources/icons/" + iconsFolder + "/ins_function.svg", 16, 16);
    public final FlatSVGIcon newBookmarkIcon = new FlatSVGIcon("resources/icons/" + iconsFolder + "/new_bookmark.svg", 16, 16);
    public final FlatSVGIcon nextBookmarkIcon = new FlatSVGIcon("resources/icons/" + iconsFolder + "/next_bookmark.svg", 16, 16);
    public final FlatSVGIcon prevBookmarkIcon = new FlatSVGIcon("resources/icons/" + iconsFolder + "/prev_bookmark.svg", 16, 16);
    
    // Code editor view
    public RSyntaxTextArea editorTextArea = new RSyntaxTextArea();
    public RTextScrollPane editorTextAreaScroller = new RTextScrollPane(editorTextArea);
    
    /**
     * Creates new form CodeEditorPanel
     */
    public CodeEditorPanel() {
        initComponents();
        
        switch(fileExtension) {
            case ".h" -> {
                editorTextArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_C);
                editorTextArea.setCodeFoldingEnabled(true);
                break;
            }
            
            case ".c" -> {
                editorTextArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_C);
                editorTextArea.setCodeFoldingEnabled(true);
                break;
            }
            
            case ".cpp" -> {
                editorTextArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_CPLUSPLUS);
                editorTextArea.setCodeFoldingEnabled(true);
                break;
            }
            
            case ".ini" -> {
                editorTextArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_INI);
                editorTextArea.setCodeFoldingEnabled(true);
                break;
            }
            
            default -> {
                break;
            }
        }

        this.add(editorTextAreaScroller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CodeEditorToolbar = new javax.swing.JToolBar();
        FunctionsListLabel = new javax.swing.JLabel();
        FunctionsListButton = new javax.swing.JComboBox<>();
        ToolbarSeparator10 = new javax.swing.JToolBar.Separator();
        GoToButton = new javax.swing.JButton();
        ToolbarSeparator11 = new javax.swing.JToolBar.Separator();
        InsertStructureButton = new javax.swing.JButton();
        InsertEnumButton = new javax.swing.JButton();
        InsertFunctionButton = new javax.swing.JButton();
        ToolbarSeparator12 = new javax.swing.JToolBar.Separator();
        NewBookmarkButton = new javax.swing.JButton();
        PrevBookmarkButton = new javax.swing.JButton();
        NextBookmarkButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        CodeEditorToolbar.setRollover(true);
        CodeEditorToolbar.setPreferredSize(new java.awt.Dimension(600, 26));

        FunctionsListLabel.setText(" Current function: ");
        CodeEditorToolbar.add(FunctionsListLabel);

        CodeEditorToolbar.add(FunctionsListButton);
        CodeEditorToolbar.add(ToolbarSeparator10);

        GoToButton.setIcon(goToViewIcon);
        GoToButton.setToolTipText("Go to");
        GoToButton.setFocusable(false);
        GoToButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GoToButton.setMaximumSize(new java.awt.Dimension(24, 24));
        GoToButton.setMinimumSize(new java.awt.Dimension(24, 24));
        GoToButton.setPreferredSize(new java.awt.Dimension(24, 24));
        GoToButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CodeEditorToolbar.add(GoToButton);
        CodeEditorToolbar.add(ToolbarSeparator11);

        InsertStructureButton.setIcon(structureInsertIcon);
        InsertStructureButton.setToolTipText("Insert structure");
        InsertStructureButton.setFocusable(false);
        InsertStructureButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InsertStructureButton.setMaximumSize(new java.awt.Dimension(24, 24));
        InsertStructureButton.setMinimumSize(new java.awt.Dimension(24, 24));
        InsertStructureButton.setPreferredSize(new java.awt.Dimension(24, 24));
        InsertStructureButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CodeEditorToolbar.add(InsertStructureButton);

        InsertEnumButton.setIcon(enumerationInsertIcon);
        InsertEnumButton.setToolTipText("Insert enumeration");
        InsertEnumButton.setFocusable(false);
        InsertEnumButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InsertEnumButton.setMaximumSize(new java.awt.Dimension(24, 24));
        InsertEnumButton.setMinimumSize(new java.awt.Dimension(24, 24));
        InsertEnumButton.setPreferredSize(new java.awt.Dimension(24, 24));
        InsertEnumButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CodeEditorToolbar.add(InsertEnumButton);

        InsertFunctionButton.setIcon(functionInsertIcon);
        InsertFunctionButton.setToolTipText("Insert function");
        InsertFunctionButton.setFocusable(false);
        InsertFunctionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InsertFunctionButton.setMaximumSize(new java.awt.Dimension(24, 24));
        InsertFunctionButton.setMinimumSize(new java.awt.Dimension(24, 24));
        InsertFunctionButton.setPreferredSize(new java.awt.Dimension(24, 24));
        InsertFunctionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CodeEditorToolbar.add(InsertFunctionButton);
        CodeEditorToolbar.add(ToolbarSeparator12);

        NewBookmarkButton.setIcon(newBookmarkIcon);
        NewBookmarkButton.setToolTipText("Add new bookmark");
        NewBookmarkButton.setFocusable(false);
        NewBookmarkButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NewBookmarkButton.setMaximumSize(new java.awt.Dimension(24, 24));
        NewBookmarkButton.setMinimumSize(new java.awt.Dimension(24, 24));
        NewBookmarkButton.setPreferredSize(new java.awt.Dimension(24, 24));
        CodeEditorToolbar.add(NewBookmarkButton);

        PrevBookmarkButton.setIcon(prevBookmarkIcon);
        PrevBookmarkButton.setToolTipText("Preview bookmark");
        PrevBookmarkButton.setFocusable(false);
        PrevBookmarkButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PrevBookmarkButton.setMaximumSize(new java.awt.Dimension(24, 24));
        PrevBookmarkButton.setMinimumSize(new java.awt.Dimension(24, 24));
        PrevBookmarkButton.setPreferredSize(new java.awt.Dimension(24, 24));
        PrevBookmarkButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CodeEditorToolbar.add(PrevBookmarkButton);

        NextBookmarkButton.setIcon(nextBookmarkIcon);
        NextBookmarkButton.setToolTipText("Next bookmark");
        NextBookmarkButton.setFocusable(false);
        NextBookmarkButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NextBookmarkButton.setMaximumSize(new java.awt.Dimension(24, 24));
        NextBookmarkButton.setMinimumSize(new java.awt.Dimension(24, 24));
        NextBookmarkButton.setPreferredSize(new java.awt.Dimension(24, 24));
        NextBookmarkButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CodeEditorToolbar.add(NextBookmarkButton);

        add(CodeEditorToolbar, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar CodeEditorToolbar;
    private javax.swing.JComboBox<String> FunctionsListButton;
    private javax.swing.JLabel FunctionsListLabel;
    private javax.swing.JButton GoToButton;
    private javax.swing.JButton InsertEnumButton;
    private javax.swing.JButton InsertFunctionButton;
    private javax.swing.JButton InsertStructureButton;
    private javax.swing.JButton NewBookmarkButton;
    private javax.swing.JButton NextBookmarkButton;
    private javax.swing.JButton PrevBookmarkButton;
    private javax.swing.JToolBar.Separator ToolbarSeparator10;
    private javax.swing.JToolBar.Separator ToolbarSeparator11;
    private javax.swing.JToolBar.Separator ToolbarSeparator12;
    // End of variables declaration//GEN-END:variables
}